version: '3.9'

x-shared-volumes: &shared-volumes
  - .:/app

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    volumes: *shared-volumes
    working_dir: /app
    stdin_open: true
    tty: true

