version: '3.9'

x-shared-volumes: &shared-volumes
  - .:/app
  - node_modules:/app/node_modules

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    volumes: *shared-volumes
    working_dir: /app
    stdin_open: true
    tty: true

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

volumes:
  node_modules:
